cbv/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('school.urls')),
]

school/urls.py
from django.urls import path
from . import views

app_name = 'school'

urlpatterns = [
    # path('cbv/',views.CBView.as_view(),name='index'),
    # path('',views.IndexView.as_view(),name='indexview'),

    # CRUD 
    path('',views.IndexView.as_view(),name='index'),
    path('list/',views.SchoolListView.as_view(),name='list'),
    path('list/<int:pk>/',views.SchoolDetailView.as_view(),name='detail'),
    path('create/',views.SchoolCreateView.as_view(),name='create'),
    path('update/<int:pk>/',views.SchoolUpdateView.as_view(),name='update'),
    path('delete/<int:pk>/',views.SchoolDeleteView.as_view(),name='delete'),
    
]

school/models.py
from django.db import models
from django.urls import reverse

class School(models.Model):
    name = models.CharField(max_length=50)
    princlipal = models.CharField(max_length=50)
    location = models.CharField(max_length=250)

    def __str__(self):
        return self.name

    # CreateView Part
    # we need this when url error shown then use 'reverse'

    # def get_absolute_url(self):
    #     return reverse("school:detail",kwargs={'pk':self.pk})
    # or use success_url in views.py

class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School,related_name='students',on_delete=models.CASCADE)

    def __str__(self):
        return self.name

school/views.py
from django.db.models import fields
from django.http.response import HttpResponse
from django.shortcuts import redirect, render
from django.views.generic import (View,TemplateView,
                                ListView,DetailView,
                                UpdateView,DeleteView)
from django.views.generic.edit import CreateView
from school import models
from school.models import School
from django.urls import reverse_lazy

# class CBView(View):
#     def get(self,request):
#         return HttpResponse("Class Based View Example")

# Practic again
# class IndexView(TemplateView):
#     template_name  = 'school/index.html'

#     def get_context_data(self, **kwargs):
#         context = super().get_context_data(**kwargs)
#         context['injectme'] = 'BASIC INJECTION!'
#         return context

class IndexView(TemplateView):
    template_name = 'school/home.html'

# Note - context_object_name,model,template_name
# these are the built-in classes of CBV 


class SchoolListView(ListView):
    context_object_name = 'schools'
    model = School
    # If you don't mention template path
    # it will take default template
# template path must be started templates/appname/_.html in CBV

class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = School
    template_name = 'school/school_detail.html'

class SchoolCreateView(CreateView):
    fields = ('name','princlipal','location')
    model = School
    # use to reverse url
    success_url = reverse_lazy("school:list")

class SchoolUpdateView(UpdateView):
    fields = ('name','princlipal')
    model = School
    success_url = reverse_lazy("school:list")


class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy("school:list")

templates/base/base-template.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    
    <title>CBV</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="navbar-nav">
          <a class="navbar-brand" href="{{BASE_URL}}">Index</a>         
          <a class="navbar-brand" href="{{BASE_URL}}list/">Schools</a>
          <a class="nav-item nav-link" href="{{BASE_URL}}admin/">Admin</a>
          <a class="nav-item nav-link" href="{{BASE_URL}}create/">Create School</a>
        </div>
      </nav>

    {% block content %}
    {% endblock %}

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

templates/school/home.html
{% extends 'school/school_base.html' %}

{% block content %}
<h3>Home Page</h3>
{% endblock %}

templates/school/index.html
{% extends 'base/base-template.html' %}

{% block content %}
<h4>Index Page</h4>
<h2>Injected Content: {{ injectme }}</h2>
{% endblock %}

templates/school/school_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css"
    integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    
    <title>CBV</title>
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="navbar-nav">
          <!-- <a class="navbar-brand" href="{{BASE_URL}}">Index</a>          -->
          <a class="navbar-brand" href="{% url 'school:list' %}">Schools</a>
          <a class="nav-item nav-link" href="{% url 'admin:index' %}">Admin</a>
          <a class="nav-item nav-link" href="{% url 'school:create' %}">Create School</a>
        </div>
      </nav>

      <div class="container">
    {% block content %}
    {% endblock %}
  </div>
</body>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>

</html>

templates/school/school_confirm_delete.html
{% extends "school/school_base.html" %}

{% block content %}
<h1>Delete {{school.name}}?</h1>

<form method="post">
  {% csrf_token %}
  <input type="submit" class="btn btn-danger" value="Delete">
  <a class="btn btn-warning" href="{% url 'school:detail' pk=school.pk %} ">Cancel</a>

</form>

{% endblock %}

templates/school/school_detail.html
{% extends 'school/school_base.html' %}
{% block content %}
<div class="jumbotron">

<h4>Detail of School</h4>
<p>Name: {{school_detail.name}}</p>
<p>Principal: {{school_detail.princlipal}}</p>
<p>Location: {{school_detail.location}}</p>

<h3>Students</h3>
{% for student in school_detail.students.all %}
<p>{{student.name}} who is {{student.age}} years old.</p>
{% endfor %}

</div>

<div class="container">
    <p><a class="btn btn-warning" href="{% url 'school:update' pk=school_detail.pk %}">Update</a></p>
    <p><a class="btn btn-secondary" href="{% url 'school:delete' pk=school_detail.pk %}">Delete</a></p>
</div>

{% endblock %}

templates/school/school_form.html
{% extends "school/school_base.html" %}
{% block content %}

<h1>
    {% if not form.instance.pk %}
    Create School
    {% else %}
    Update School
    {% endif %}
</h1>

<form action="" method="POST">
    {% csrf_token %}
    {{form.as_p}}

    <input type="submit" class="btn btn-primary" value="submit">
</form>


{% endblock %}

templates/school/school_list.html
{% extends "school/school_base.html" %}
{% block content %}

  <div class="jumbotron">
    <h1>Welcome to the List of Schools Page!</h1>
      <ol>
        {% for school in schools %}
          <h2><li><a href="{{school.id}}/">{{school.name}} </a></li></h2>
        {% endfor %}
      </ol>
  </div>
{% endblock %}